homebrew_taps:
  - caskroom/cask

homebrew_packages:
  - { name: rmtrash }
  - { name: openssl }
  - { name: libxml2 }
  - { name: mcrypt }
  - { name: autoconf }
  - { name: automake }
  - { name: bison }
  - { name: chromedriver }
  - { name: docker-machine }
  - { name: jq }
  - { name: tree }
  - { name: curl }
  - { name: nkf }
  - { name: peco }
  - { name: zplug }
  - { name: parallel }
  - { name: wget }
  - { name: awscli }

homebrew_cask_packages:
  - { name: docker }
  - { name: visual-studio-code }
  - { name: phpstorm }
  - { name: atom }
  - { name: virtualbox }
  - { name: spectacle }
  - { name: alfred }
  - { name: iterm2 }
  - { name: kobito }
  - { name: slack }
